---
title: "Tidy tuesday 2019-5-28, wine ratings"
output: html_notebook
---
```{r libraries}
library(magrittr)
library(dplyr)
library(DT)
library(tidyr)
library(tagcloud)
library(RColorBrewer)
```

```{r some-config}
TOP.ENTRIES <- 50 # How many entries to plot
colors <- colorRampPalette( brewer.pal( 12, "Paired" ) )( TOP.ENTRIES ) # Colors
```

```{r}
wine.ratings <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-28/winemag-data-130k-v2.csv")
# saveRDS(wine.ratings, here::here("ratings-raw.rds"))
# wine.ratings <- readRDS(here::here("ratings-raw.rds"))
```

```{r rename-id-col}
wine.ratings %<>% rename(ID = X1)
```

```{r extract-words}
wine.ratings %<>%
  mutate(
    words = strsplit(description, split = "([\\. \\,\\;0-9\\?\\!]+)")
  )
```

```{r process-words}
words.scores <- wine.ratings %>%
  # head(10) %>%
  select(ID, points, words) %>%
  as_tibble() %>%
  unnest(
    words
  ) %>%
  mutate(
    words = tolower(words)
  ) %>%
  filter(grepl("^[^0-9]*^", words)) %>%
  filter(nchar(words) > 3)
```

```{r count-occurences}
word.occurences <- words.scores %>%
  group_by(words) %>%
  summarise(
    occurences = n()
    , occurences.unique = length(unique(ID))
  ) %>%
  ungroup() %>%
  mutate(
    rate = occurences / nrow(wine.ratings)
    , rate.unique = occurences.unique / nrow(wine.ratings)
  ) %>%
  arrange(-rate.unique)

summary(word.occurences$rate.unique)

quantile(word.occurences$rate.unique, seq(.9, 1, by = .01)) %>% as.data.frame()

word.occurences %>% head(50)
word.occurences %>% tail(50)
```

```{r remove-frequent}
words.selected <- words.scores %>%
  filter(!words %in% (word.occurences %>% filter(rate.unique > .2) %>% pull(words)))
```

```{r tagcloud-all}
count.all <- table(words.selected$words) %>% sort()
tagcloud(names(count.all) %>% tail(TOP.ENTRIES), count.all %>% tail(TOP.ENTRIES), col = colors)
```
```{r tagcloud-top-01}
q01 <- quantile(wine.ratings$points, .01)
count.q01 <- table(words.selected %>% filter(points >= q01) %>% pull(words)) %>% sort()
tagcloud(names(count.q01) %>% tail(TOP.ENTRIES), count.all %>% tail(TOP.ENTRIES), col = colors)
```
```{r tagcloud-top-05}
q05 <- quantile(wine.ratings$points, .05)
count.q05 <- table(words.selected %>% filter(points >= q05) %>% pull(words)) %>% sort()
tagcloud(names(count.q01) %>% tail(TOP.ENTRIES), count.all %>% tail(TOP.ENTRIES), col = colors)
```
